const modules={crm:{label:'RELACIÓN CON LOS CLIENTES',title:'Cada cliente, bien registrado.',description:'Una ficha centralizada permite organizar la información general, comercial y de contacto para facilitar la consulta y el seguimiento.',list:['Registro y actualización de clientes.','Consulta de datos de contacto y entrega.','Organización de condiciones comerciales y estado.'],views:[['crm','Registro de clientes','Formulario de registro de un nuevo cliente']]},inventario:{label:'PRODUCTOS Y EXISTENCIAS',title:'Saber qué hay y dónde está.',description:'El módulo organiza el catálogo y permite consultar las existencias, revisar el estado de los productos e identificar necesidades de reposición.',list:['Productos, categorías y subcategorías.','Consulta de existencias por sucursal.','Ajustes y alertas de stock bajo.'],views:[['catalogo','Catálogo','Catálogo del sistema con productos y estado de inventario'],['existencias','Existencias','Consulta de existencias y distribución por sucursal'],['alertas','Alertas','Pantalla de alertas de abastecimiento del sistema']]},admin:{label:'PERSONAS Y ACCESOS',title:'Cada función, con su acceso.',description:'La administración reúne la gestión de empleados, usuarios, sucursales, roles y permisos para organizar las responsabilidades del equipo.',list:['Registro y administración de usuarios.','Configuración de sucursales y perfiles.','Permisos de consulta, creación y modificación.'],views:[['roles','Roles','Formulario del sistema para crear un rol'],['permisos','Permisos','Matriz de permisos de clientes y administración']]}};
const $=id=>document.getElementById(id);let current='crm';function setView(view){$('module-image').src='assets/'+view[0]+'.png';$('module-image').alt=view[2];$('module-caption').textContent=view[1]+' · Vista de interfaz';$('open-image').setAttribute('aria-label','Ampliar: '+view[1]);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view[0])))}function setModule(key){current=key;const m=modules[key];document.querySelectorAll('[data-module]').forEach(b=>{const active=b.dataset.module===key;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});$('module-panel').setAttribute('aria-labelledby','tab-'+key);$('module-label').textContent=m.label;$('module-title').textContent=m.title;$('module-description').textContent=m.description;$('module-list').replaceChildren(...m.list.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('view-buttons').replaceChildren(...m.views.map(v=>{const b=document.createElement('button');b.textContent=v[1];b.dataset.view=v[0];b.onclick=()=>setView(v);return b}));setView(m.views[0])}document.querySelectorAll('[data-module]').forEach((b,i,all)=>{b.addEventListener('click',()=>setModule(b.dataset.module));b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%all.length;else if(e.key==='ArrowLeft')n=(i+all.length-1)%all.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=all.length-1;else return;e.preventDefault();all[n].focus();setModule(all[n].dataset.module)})});setModule('crm');$('open-image').onclick=()=>{$('dialog-image').src=$('module-image').src;$('dialog-image').alt=$('module-image').alt;$('dialog-title').textContent=$('module-caption').textContent;$('image-dialog').showModal();document.body.classList.add('modal-open')};$('close-dialog').onclick=()=>$('image-dialog').close();$('image-dialog').addEventListener('close',()=>{document.body.classList.remove('modal-open');$('open-image').focus()});$('image-dialog').addEventListener('click',e=>{if(e.target===$('image-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{const v=$('demo-video');v.currentTime=Number(b.dataset.time);v.play().catch(()=>{});v.focus()});

// Subtle transitions, section-aware navigation and video chapter feedback.
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if('IntersectionObserver' in window){
 const sections=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){document.querySelectorAll('nav a').forEach(a=>{const active=a.getAttribute('href')==='#'+entry.target.id;a.classList.toggle('is-active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}})},{rootMargin:'-15% 0px -55% 0px',threshold:0});
 document.querySelectorAll('#modulos,#recorrido,#beneficios').forEach(el=>sections.observe(el));
 if(!reduceMotion){const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('arrive');reveal.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.context,.modules .section-heading,.benefits-grid article').forEach(el=>reveal.observe(el))}
}
document.querySelectorAll('[data-module]').forEach(b=>b.addEventListener('click',()=>{if(!reduceMotion){const panel=$('module-panel');panel.classList.remove('is-switching');void panel.offsetWidth;panel.classList.add('is-switching')}}));
$('demo-video').addEventListener('timeupdate',()=>{const t=$('demo-video').currentTime;const chapters=[...document.querySelectorAll('[data-time]')];chapters.forEach((b,i)=>b.classList.toggle('is-playing',t>=Number(b.dataset.time)&&(i===chapters.length-1||t<Number(chapters[i+1].dataset.time))))});
// Module shortcuts and Bootstrap mobile navigation.
document.querySelectorAll('[data-open-module]').forEach(a=>a.addEventListener('click',()=>setModule(a.dataset.openModule)));
document.querySelectorAll('#main-nav a').forEach(a=>a.addEventListener('click',()=>{const n=document.getElementById('main-nav');if(window.bootstrap&&n.classList.contains('show'))bootstrap.Collapse.getOrCreateInstance(n).hide()}));
